## docker-compose.yml

version: '3.7'

x-ref: &ref
  tty: true
  working_dir: ${HOME}
  environment:
    - &env_display DISPLAY=${HOST_DISPLAY}
  volumes:
    - &vol_home ${HOME}:${HOME}
    - &vol_display /tmp/.X11-unix:/tmp/.X11-unix

services:
  elisp:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-elisp

  bashcaster:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-bashcaster

  python:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-anyenv

  go:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-anyenv

  php:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-php

  cpp:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-cpp

