## docker-compose.yml

version: '3.7'

x-ref:
  <<: &tty
    tty: true
  x-tree:
    - &vol_home ${HOME}:/home/user
    - &env_display DISPLAY=${HOST_DISPLAY}
    - &vol_display /tmp/.X11-unix:/tmp/.X11-unix

services:
  elisp:
    <<: *tty
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-elisp
    environment:
      - *env_display
    volumes:
      - *vol_display
      - *vol_home

  bashcaster:
    <<: *tty
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-bashcaster
    environment:
      - *env_display
    volumes:
      - *vol_display
      - *vol_home

  python:
    <<: *tty
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-python
    environment:
      - *env_display
    volumes:
      - *vol_display
      - *vol_home

