## docker-compose.yml

version: '3.7'

x-ref: &ref
  tty: true
  environment:
    - &env_display DISPLAY=${HOST_DISPLAY}
  volumes:
    - &vol_home ${HOME}:/home/user
    - &vol_display /tmp/.X11-unix:/tmp/.X11-unix

services:
  elisp:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-elisp

  bashcaster:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-bashcaster

  python:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-python
