## docker-compose.yml

version: '3'

services:
  elisp:
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-elisp
    tty: true
    environment:
      - DISPLAY=${HOST_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
