## docker-compose.yml

version: '3.7'

x-ref: &ref
  tty: true
  working_dir: ${HOME}
  environment:
    - &env_display DISPLAY=${HOST_DISPLAY}
  volumes:
    - &vol_display /tmp/.X11-unix:/tmp/.X11-unix
    - &vol_zshrc ${HOME}/.zshrc:${HOME}/.zshrc

services:
  elisp:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-elisp

  util:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-util
    working_dir: ${HOME}/Pictures

  python:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-anyenv

  go:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-go

  php:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-php

  cpp:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-cpp

  lisp:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-lisp
