## docker-compose.yml

version: '3.7'

x-ref: &ref
  tty: true
  working_dir: ${HOME}
  environment:
    - &env_display DISPLAY=${HOST_DISPLAY}
  volumes:
    - &vol_config ${HOME}/.config:${HOME}/.config
    - &vol_debugemacs ${HOME}/.emacs.d:${HOME}/.debug.emacs.d
    - &vol_dev ${HOME}/dev:${HOME}/dev
    - &vol_display /tmp/.X11-unix:/tmp/.X11-unix
    - &vol_docker ${HOME}/.emacs.d:${HOME}/docker
    - &vol_emacs ${HOME}/.emacs.d:${HOME}/.emacs.d
    - &vol_gpg ${HOME}/.gnupg:${HOME}/.gnupg
    - &vol_gpgagent /run/user/${LOCAL_UID}/:/run/user/${LOCAL_UID}/:ro
    - &vol_secret ${HOME}/.secret:${HOME}/.secret
    - &vol_ssh ${HOME}/.ssh:${HOME}/.ssh
    - &vol_zshrc ${HOME}/.zshrc:${HOME}/.zshrc

x-ref2:
  volumes:
    - &vol_pictures ${HOME}/Pictures:${HOME}/Pictures

services:
  elisp:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-elisp

  util:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-util
    working_dir: ${HOME}/Pictures
    volumes: [*vol_config, *vol_dev, *vol_display, *vol_docker, *vol_emacs,
              *vol_gpg, *vol_gpgagent, *vol_secret, *vol_ssh, *vol_zshrc,
              *vol_pictures]

  python:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-python

  atcoder:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-atcoder

  go:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-go

  php:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-php

  cpp:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-cpp

  lisp:
    <<: *ref
    build:
      context: docker
      dockerfile: Dockerfile-archlinux-lisp
