## Dockerfile-archlinux-php

FROM conao3/archlinux-basedevel:latest

RUN yay -Sy --noconfirm apache postgresql mysql sqlite composer npm && \
    yay -Scc --noconfirm

# intelephense is lsp of php
# unzip is needed by phpstan

RUN sudo npm install -g intelephense vscode-html-languageserver-bin \
        vscode-css-languageserver-bin && \
    yay -S --noconfirm unzip && \
    composer global require phpstan/phpstan phpactor/phpactor
