## Dockerfile-archlinux-lisp

FROM conao3/archlinux-basedevel:latest

RUN yay -S --noconfirm roswell-git && \
    yay -Scc --noconfirm

ENV PATH=$HOME/.roswell/bin:$PATH

RUN ros setup
RUN ros install fukamachi/rove
