## Dockerfile-basedevel

FROM conao3/archlinux:latest

# emacs dependency
# https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/emacs#n11

# depends=('librsvg' 'gpm' 'giflib' 'libxpm' 'libotf' 'm17n-lib'
#          'gtk3' 'hicolor-icon-theme' 'desktop-file-utils'
#          'alsa-lib' 'gnutls' 'jansson' 'cairo' 'harfbuzz')

# hide this GTK warning
# (emacs:17): dbind-WARNING **: 20:11:50.214: Couldn't connect to
# accessibility bus: Failed to connect to socket
# /tmp/dbus-2ctEtuGB1e: Connection refused

ENV NO_AT_BRIDGE=1
ENV SHELL=/bin/zsh

RUN yay -S --noconfirm emacs && \
    yay -S --noconfirm \
        zsh tree powerline-go hub w3m fd fzf ripgrep tmux xsel \
        tokei aws-cli && \
    yay -Scc --noconfirm
