## Dockerfile-archlinux-bashcaster

FROM conao3/archlinux-basedevel:latest

# bashcaster dependency
# https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bashcaster-git

# depends=("ffmpeg" "xorg-xprop" "xorg-xwininfo" "yad")

RUN yay -S --noconfirm bashcaster-git && \
    yay -Scc --noconfirm
