## Dockerfile-archlinux-slack

FROM conao3/archlinux:latest

# slack
# https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=slack-desktop#n12
# depends=('alsa-lib' 'gtk3' 'libsecret' 'libxss' 'libxtst'
#          'nss' 'xdg-utils')

RUN yay -Syyu --noconfirm libxkbfile firefox && \
    yay -Syyu --noconfirm slack-desktop && \
    yay -Scc --noconfirm
